apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ads-dental-surgery
resources:
  - ../../base
  - secrets.yaml
  - ingress.yaml
images:
  - name: kshitijgrg/ads-dental-surgery
    newTag: sha-a435eb6
