apiVersion: v1
kind: Secret
metadata:
  name: ads-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change-me-in-cluster
  DB_PASSWORD: change-me-in-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: ads-app-secret
type: Opaque
stringData:
  JWT_SECRET: change-me-in-cluster
