apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ads-dental-surgery
resources:
  - ../../base
  - secrets.yaml
patches:
  - target:
      kind: Service
      name: ads-api
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
images:
  - name: kshitijgrg/ads-dental-surgery
    newTag: sha-a435eb6
